### ISSUE TITLE
can not import 

### ISSUE THREAD

**Issue by joeyczz** [MikeMcl/bignumber.js#166] opened 2018-05-19 08:09 UTC
can not import bignumber by "import BigNumber from 'bignumber.js';" in version 7.1.0

**Comment by Nufflee** [comment] 2018-05-19 12:10
I can import but it throws `TypeError: bignumber_js_1.BigNumber is not a constructor` when using `new BigNumber(..)`

**Comment by Hokid** [comment] 2018-05-19 12:37
i have found workaround:
```
import BigNumber from 'bignumber.js/bignumber';
```

**Comment by wenner** [comment] 2018-05-19 17:02
7.0.1 , 7.0.2 work fine

but 7.1.0 , The following error occurred
> "export 'BigNumber' was not found in 'bignumber.js'

**Comment by 6gunner** [comment] 2018-05-21 10:52
when i use `import BigNumber from 'bignumber.js/bignumber.mjs'`
it throw error: 
__WEBPACK_IMPORTED_MODULE_1_bignumber_js_bignumber_mjs__.a is not a constructor"

**Comment by akostiv** [comment] 2018-05-21 14:31
Looks like that `BigNumber` variable is never assigned in .mjs file
adding `BigNumber = clone()` before `export default BigNumber` solved the issue for me.
But I am not sure whether it is correct fix or not

**Comment by benwiggins** [comment] 2018-05-21 22:07
create-react-app's webpack config has issues with .mjs files, eg. 
https://github.com/szimek/signature_pad/issues/257
https://github.com/icd2k3/react-router-breadcrumbs-hoc/pull/14

With the change in 7.1.0 I now have to explicitly load the .js version.
`import { BigNumber } from 'bignumber.js/bignumber.js';`

**Comment by MikeMcl** [comment] 2018-05-21 22:26
Yes, @akostiv is right. It seems I accidentally removed the `BigNumber = clone()` from *bignumber.mjs* in *v7.0.0*. I will fix tomorrow.

That still will leave the problem of node.js not supporting the `module` field in the *package.json*, so it won't find the *bignumber.mjs* file if you just do import `BigNumber from 'bignumber.js'`.

Further information on that still to be digested at these links:
https://github.com/nodejs/node/issues/17300
https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#44-shipping-both-esm-and-cjs
https://github.com/nodejs/node-eps/pull/60
https://github.com/nodejs/node-eps/blob/master/002-es-modules.md

**Comment by MikeMcl** [comment] 2018-05-22 11:00
Just published *v7.2.0* which should fix the `import` issues.

**Comment by Falieson** [comment] 2018-05-28 16:11
Or you could do
```
import {BigNumber} form 'bignumber.js'
```

**Comment by STayinloves** [comment] 2018-05-29 07:33
This issue still exists as I'm using the latest v7.2.1 version and `import {BigNumber} from 'bignumber.js'`.
The workaround
```
import BigNumber from 'bignumber.js/bignumber';
```
does work.

**Comment by bodymindarts** [comment] 2018-05-29 08:16
For me I'm having issues loading bignumber with Jest while testing though bundling it with webpack for production seems to work.

**Comment by Nufflee** [comment] 2018-05-29 12:21
You should probably open a new issue for this with more information. @bodymindarts

**Comment by MikeMcl** [comment] 2018-05-29 19:41
To get anywhere with these import issues much more detail is required about the context in whicih this library is loaded - node.js/browser/bundler/transpiler/typescript etc.

Anyway, I am considering going back to the original, simpler configuration, i.e. removing the `module` and `browser` fields from the *package.json*, changing `main: 'bignumber'` back to `main: 'bignumber.js'`, and moving the *bignumber.mjs* file to its own directory so it won't be loaded by mistake.

**Comment by dawka** [comment] 2018-05-30 14:28
I am on version 7.2.1 and trying to use the library inside the angular app, so it is TypeScript.

I am using the following import:
`import BigNumber from 'bignumber.js/bignumber';`
it does resolve 'is not a constructor' issue, so constructing BigNumber works fine, but calling isEqualTo gives 'isEqualTo is not a function' error.

Any ideas? Let me know if you need anything else, I am happy to assist you with providing more details if needed.

Is there any lib version that does not have these issues in typescript environment? I would be happy to downgrade.

**Comment by MikeMcl** [comment] 2018-05-30 16:47
@dawka 

If `isEqualTo` is not a function it sounds like you are using an older version of this library.

Typescript imports work just fine: you can use just the standard `import BigNumber from "bignumber.js"` or `import {BigNumber} from "bignumber.js"` loading from a *node_modules* folder.

The issue is probably with the "inside the angular app" part and/or your project's configuration. I am not familiar with angular. If you open a new issue on this and provide fuill details someone may be able to help.

**Comment by Falieson** [comment] 2018-06-01 00:04
My bad, I'm using typescript! So the import works fine, sorry I didn't specify that (or realize that is whats resolving the issue for me).

**Closed** 2018-10-22 21:22 UTC

**Comment by cliffhall** [comment] 2019-08-13 15:54
Still seeing this when trying to use bignumber.js in React.

```
npm install bignumber.js --save
...
+ bignumber.js@9.0.0
added 1 package and updated 1 package in 42.022s
```

In MyEntity.js:
```
import BigNumber from "./bignumber.mjs";
```

Webstorm hint:
```
Cannot resolve file 'bignumber.mjs' 
```
Running MyEntityTest.js with jest:
```
Cannot find module './bignumber.mjs' from 'MyEntity.js'
```
