### ISSUE TITLE
Is it possible to compare to instances by actual value?

### ISSUE THREAD

**Issue by karfau** [MikeMcl/bignumber.js#73] opened 2015-09-28 13:09 UTC
In the following scenario

    BigNumber.config(6, BigNumber.ROUND_HALF_UP);
    var a = new BigNumber("0.000001”);
    var b = a.dividedBy(2);

The actual value of `a` and `b` are the same, as the e.e. both return `0.000001` from `toString()`.

But when I compare them `a.comparedTo(b);` it returns `1` as such of course `a.equals(b)` returns `false`.

Is that an expected behaviour, because I couldn't find something in the docs of `comparedTo` or `equal` that speak about this case.
And if it is, is there a way (in the API of bignumber.js) to compare against the actual value without doing a string conversion?

**Comment by MikeMcl** [comment] 2015-10-01 22:26
Hi,
Sorry for the delay. I didn't receive a notification about this issue for some reason.
No, this is not expected behaviour. It is a bug and its disappointing.
I will fix ASAP.

**Comment by MikeMcl** [comment] 2015-10-02 11:19
Fixed in v2.0.8

Thanks very much for the report.

Notes:
This is the second bug that has been discovered since the switch to using a higher base internally. The test cases did not reveal it because they mostly just check the string representation and not the actual values of the properties of each big number after an operation. This bug showed that numbers of the form 0.1, 0.01, 0.001 etc. may not have the correct internal representation if they arose as the result of rounding after a division operation. The string representation of the numbers would be correct, but their internal inconsistency (the first value of the coefficient array could be the wrong power of ten) could cause the `comparedTo` method to produce incorrect results.

**Closed by MikeMcl** 2015-10-02 11:19 UTC

**Comment by karfau** [comment] 2015-10-06 07:51
are you going to publish this version so it can be updated via npm, or do I need to update it manually?

**Comment by MikeMcl** [comment] 2015-10-06 08:35
I've done it. Thanks for the reminder.

**Comment by karfau** [comment] 2015-10-06 09:28
:+1: thx
