### ISSUE TITLE
Infinite loop in Safari 10.1

### ISSUE THREAD

**Issue by minichate** [MikeMcl/bignumber.js#120] opened 2017-03-29 05:02 UTC
There appears to be an infinite loop in https://github.com/MikeMcl/bignumber.js/blob/46ed093a78e4061efeac50c1bbae624ad61a33f2/bignumber.js#L918-L925 for new versions of Webkit, including the newly released Safari 10.1

```
(new BigNumber(2043150)).dividedBy(10000);
```

**Comment by Ka0o0** [comment] 2017-03-29 07:12
I can confirm this bug. 

Just found out that divisions work for small divisors though.

**Comment by MikeMcl** [comment] 2017-03-29 09:26
Thanks for the report.

This would seem to be a bug in Safari 10.1.

Unfortunately, I cannot investigate this at the moment as I don't have access to that browser.

I wonder if it is the ternary expression in the `subtract` call that it is having problems with.
```js
while ( compare( prod, rem, prodL, remL ) == 1 ) {
    n--;

    // Subtract divisor from product.
    subtract( prod, yL < prodL ? yz : yc, prodL, base );
    prodL = prod.length;
    cmp = 1;
}
```

Please could someone try putting braces around it, i.e.
```js
    subtract( prod, ( yL < prodL ? yz : yc ), prodL, base );
```

**Comment by yukihirog** [comment] 2017-03-29 09:33
Please check length of 'rem'.

Line 972~
```
                        // Update the remainder.
                        if ( rem[0] ) {
                            rem[remL++] = xc[xi] || 0;
                        } else {
```

Sometimes length is deferent from true length in Safari 10.1.
I tryed this code.

```
                        // Update the remainder.
                        if ( rem[0] ) {
                            rem[remL++] = xc[xi] || 0;
var ___i = 0;
while (!isNaN(rem[___i])) {
    ___i++;
}
rem.length = ___i;
remL = rem.length;
                        } else {
```

**Comment by MikeMcl** [comment] 2017-03-29 10:01
@yukihirog 

And does it work?

Do the following equivalent alternatives work
```js
if ( rem[0] ) {
    rem[remL] = xc[xi] || 0;
    remL++;
} else {
```
or 

```js
if ( rem[0] ) {
    rem[remL] = xc[xi] || 0;
    remL = rem.length;
} else {
```

**Comment by Ka0o0** [comment] 2017-03-29 10:03
@MikeMcl just tried your suggestions. While the first won't work the second doesn't produce an endless loop.

**Comment by yukihirog** [comment] 2017-03-29 10:12
@MikeMcl thank you.
In my case, second code is works.

I checked on console.
```
                        if ( rem[0] ) {
                            rem[remL++] = xc[xi] || 0;
console.log(rem, rem[0], rem[1], rem.length);
```

In Safari 10.1:
[40000000000000], 40000000000000, 0, 1
(rem[1] is 0. but length is 1.)

Other browsers:
[40000000000000, 0], 40000000000000, 0, 2

**Comment by MikeMcl** [comment] 2017-03-29 10:58
> (rem[1] is 0. but length is 1.)

Strange.

Please try

```js
if ( rem[0] ) {
    console.log(rem, rem.length, remL, xc[xi]);
    rem[remL++] = xc[xi] || 0;
    console.log(rem, rem.length, remL);
} else {
```

**Comment by yukihirog** [comment] 2017-03-29 11:07
nmm...

results:
  before:
    rem=[40000000000000], rem.length=1, remL=1, xc[xi]=undefined
  after:
    rem=[40000000000000], rem.length=1, remL=2

**Comment by yukihirog** [comment] 2017-03-29 11:13
my case is
```
var num = new BigNumber(670);
num.div(4);
```

**Comment by MikeMcl** [comment] 2017-03-29 11:19
@yukihirog 

Thank you.
It seems to be a bug in the JavaScript engine of the browser.

If `rem.length` and `remL` is `1` before, then `rem[remL++] = xc[xi] || 0;` shoud do `rem[1] = 0` which should mean that `rem` then becomes `[40000000000000, 0]` with a length of `2`.

Does `rem[remL++] = ( xc[xi] || 0 );` work?

**Comment by yukihirog** [comment] 2017-03-29 11:31
@MikeMcl 

rem[1] = 0, but rem becomes [40000000000000] with a length of 1.
I thought same, it seems bug in the browser...

**Comment by MikeMcl** [comment] 2017-03-29 11:34
Does the following minimal test case log `true` in the Safari 10.1 browser?

```js
var a = [0];
var aL = a.length;
a[aL] = 1;
console.log( a.length === 2 );
```

**Comment by MikeMcl** [comment] 2017-03-29 11:36
@yukihirog 

Please try
```js
if ( rem[0] ) {
    rem[remL++] = ( xc[xi] || 0 );
} else {
```

**Comment by yukihirog** [comment] 2017-03-29 11:41
```
console.log( a.length === 2 ); // true
```

but ```rem[remL++] = ( xc[xi] || 0 );``` doesn't works.

**Comment by MikeMcl** [comment] 2017-03-29 11:44
@yukihirog 

Thanks. 
One more, please.

Another minimal test case.

```js
var a = [0];
var aL = a.length;
a[aL++] = undefined || 0;
console.log( a.length === 2 );
```

**Comment by yukihirog** [comment] 2017-03-29 11:47
@MikeMcl result ```true```...

**Comment by MikeMcl** [comment] 2017-03-29 11:51
Okay, I give up for now.

Thanks for your help.

I don't understand why it produces the earlier results.

```js
if ( rem[0] ) {
    console.log(rem, rem.length, remL, xc[xi]);
    rem[remL++] = xc[xi] || 0;
    console.log(rem, rem.length, remL);
} else {
```

> before:
> rem=[40000000000000], rem.length=1, remL=1, xc[xi]=undefined
> after:
> rem=[40000000000000], rem.length=1, remL=2

**Comment by Ka0o0** [comment] 2017-03-29 12:23
Okay seems like Safari doesn't like setting new elements using an index that does not yet exist. I tried replacing `rem[remL++] = xc[xi] || 0;` with 

`
rem.push(xc[xi] || 0);
remL = remL + 1;
`

and now it seems to work. I will try the provided test cases to see whether this breaks any functionality and report back later.

**Comment by yukihirog** [comment] 2017-03-29 12:58
thank you.
it bugs in the browser.
Array#shift
```
var arr = [0, 2147483648];
arr.shift(); // arr is [2147483648]
arr[1] = 1; // arr is [2147483648, 1]
console.log(arr); // arr is [2147483648, 1], but [2147483648] in Safari 10.1
```

(smaller 2147483647, it works collectly.)
```
var arr = [0, 2147483647];
arr.shift(); // arr is [2147483647]
arr[1] = 1; // arr is [2147483647, 1]
console.log(arr); // arr is [2147483647, 1] in all browsers.
```

fix to bug
```
var arr = [0, 2147483648];
arr.shift();
arr = arr.slice(); // fix to bug
arr[1] = 1;
console.log(arr); // arr is [2147483648, 1]
```

I'll trying report to Apple.

**Comment by MikeMcl** [comment] 2017-03-29 14:42
@yukihirog 

Well done, sir.

**Comment by MikeMcl** [comment] 2017-03-29 14:59
@Ka0o0 

Yes, that code will work and not break anything because it is exactly equivalent.

**Comment by calvinlough** [comment] 2017-03-30 01:09
I logged it as a webkit bug here: https://bugs.webkit.org/show_bug.cgi?id=170264

+1's on the bug ticket would be appreciated.

**Comment by MikeMcl** [comment] 2017-03-30 09:37
@calvinlough 

How do you put a +1 on the bug ticket?

**Comment by patrickcate** [comment] 2017-04-10 02:55
Does anyone know if this bug is present in the latest version of iOS Safari and/or the WKWebView component for embedded browsers in iOS apps?

**Comment by ronknott** [comment] 2017-04-10 10:00
In iOS 10.3 and 10.3.1 the bug is in Safari,  Firefox and Chrome on iPad and iPhone.
It was not there in 10.2 versions in those browsers on those devices.
BigNumbers.js works fine on Apple laptop with latest OS.

**Comment by richardaday** [comment] 2017-04-13 18:26
Is there any simple patch that can be made to bignumber.js to work around the Safari bug?  Or is this a situation where we will wait for Safari to fix the root cause?

Thank you!

**Comment by Ka0o0** [comment] 2017-04-14 10:04
I implemented the workaround I suggested in my fork. You could use it as a temporary workaround

https://github.com/Ka0o0/bignumber.js

**Comment by MikeMcl** [comment] 2017-04-14 11:44
@richardaday 

I'll look into this again this weekend. 

@ronknott 

Thanks for the info. Do you know if the bug is still present in iOS 10.3.2 Beta 2 released a few days ago?

**Comment by ronknott** [comment] 2017-04-14 16:18
I have not tried Beta 2, but on retrying BigNumber.js on my laptop (which previously did not have problems) I discovered that if I forget to explicitly set DECIMAL_PLACES then it takes a very long time to do the first computation. This was only on Safari but not on other browsers on an Apple laptop.
From the documentation I  could not find a way to see the current default value of DECIMAL_PLACES.  Is there a way?
Once it was set, the computations seems to be back to almost instantaneous.
Hope that helps

Ron Knott

**Comment by MikeMcl** [comment] 2017-04-14 16:28
@ronknott 

```js
BigNumber.config().DECIMAL_PLACES
```

Please could you confirm if this code works on iOS.
I just want to see if the `shift` used in a post above is necessary to reproduce the bug.

```js
var arr = [2147483648];
arr[1] = 1;     
console.log(arr);     // should be [2147483648, 1]
```

**Comment by ronknott** [comment] 2017-04-17 10:08
Sorry for delay. That works fine but I didnt use console.log()
Ron

**Comment by army8735** [comment] 2017-04-18 03:09
```js
var arr = [2147483648];
arr[1] = 1;     
console.log(arr);     // should be [2147483648, 1]
```
```js
var arr = [2147483648];
arr[2] = 1;     
console.log(arr);     // should be [2147483648, undefined, 1]
```
I have run the codes on iphone with iOS 10.3.1, both of them worked correctly.

**Comment by krachtstefan** [comment] 2017-04-18 20:31
I spend hours to spot the infinite loop source :) The patch from @Ka0o0 worked for me.

**Comment by jimmoy** [comment] 2017-04-19 17:53
Can confirm @Ka0o0's patch works for me, running with a react-native app running on iOS 10.3.

**Comment by MikeMcl** [comment] 2017-04-19 18:27
Yes, I know that using `push` instead of bracket notation *seems*  to fix the issue, but just because the infinite loop dissappears doesn't mean that the results of calculations are reliable. Adding to arrays using bracket notation is used in several places in the library.

The issue seems only to appear after the array has had `shift` called upon it, so it may be better to remove the `shift` call in the inner `subtract` function of the division function.

Anyway, I am reluctant to do anything without a better understanding of the bug. I know it has been fixed in WebKit, but does anybody know if the bug has been reported to Apple and of any response? It is ridiculous that one of the richest companies in the world has released an OS/browser which fails to implement basic JavaScript array operations correctly.

**Comment by minichate** [comment] 2017-04-19 18:29
@MikeMcl I think "Fixed in WebKit nightlies" is probably the best we can hope for at this point. Given the cycle-length of Safari releases I doubt the fix will make it out to users any time soon.

Can I (or others, too!) help with auditing/testing a fix?

**Comment by Rebulus** [comment] 2017-04-26 19:11
@Ka0o0, could you create pull request from your fork? Maybe, @MikeMcl will confirm its.

**Comment by ronknott** [comment] 2017-04-27 14:04
I have not reported it to Apple.  An update to 10.3.2 is in Beta but I have not downloaded that.
Have anyone reported it?  Someone with a better idea than me of what the bug is would be better in order to describe the problem more succinctly - in the hope that they could therefore identify the issue better.
 Ron Knott
PS I have a library of other maths functions using BigNumber (gcd, log, trig and inverses, hyperbolic trig with inverse functions) that works quite quickly if you are interested.  I am new to GitHub and not sure how I could upload it.

**Comment by MikeMcl** [comment] 2017-04-27 19:30
@ronknott 

Yes, Ron, please create a Github repository of your library of math functions. There is plenty of information online on how to do this. I can then link to it from this library. 

I notice that you are the author of the wonderful continued fractions pages I have long had bookmarked. Great material, that I hope to be able to study closer at some point.

I know the bug has been reported to WebKit, and is fixed there, but I just wondered it had been reported to Apple also, and if they had given any information about when a fix was coming.

Unfortunately, as well as being undecided about what to do about this bug, I am behind in other work, so a fix is not imminent here.

**Comment by jamsinclair** [comment] 2017-05-02 23:13
Mimicking shift via splice seems to work in affected Apple browsers:
```javascript 
var arr = [0, 2147483648]; 
arr.splice(0, 1);
arr[1] = 1;

// This will evaluate true in Safari and is expected
expect(arr).toEqual([2147483648, 1])
```

@MikeMcl I understand you'd rather have this issue resolved by Apple, but after 30 day it seems in limbo whether this is happening soon.

I have a fork and PR here #122. Should hopefully allow reliable calculations with bignumber.js in affected Apple browsers. 

Let me know if I can make any changes or help 😄

**Comment by dfrencham** [comment] 2017-05-03 05:20
@jamsinclair I can confirm that Safari 10.1 fails and hangs with and without your change. It also hangs with your original change (using array push).

I can also confirm the original issue goes away with Safari 10.2 preview.

**Comment by dfrencham** [comment] 2017-05-03 06:05
Here are my results when running **every-test.html** in Safari 10.1

Test suites causing browser crash

- div
- divToInt
- mod
- pow
- sqrt
- toFraction

Test suites with failing tests:

- base-out
- minus
- plus
- round
- toDigits
- toExponential
- toFixed
- toPrecision

**Comment by jamsinclair** [comment] 2017-05-03 12:42
Amazing! Thanks for diligent testing @dfrencham 💯 

Your isolation of failing tests lead me to discover that the `.unshift()` method is also affected.
I've yet to find exact code to replicate the bug, but changing the unshift here to an alternative allowed `base-out` tests to pass. Changing the rest fixed the test suite. 
 
I've added a workaround to my fork using `Array.prototype.concat` to mimic unshift. The tests now *ALL PASS* on **Safari 10.1** for myself locally 🎉 . Are you able to confirm validity of tests? 😄

These workarounds have probably slowed the performance down a little as native shift/unshift will be faster.  

The failing test suites above worry me greatly. I think it's safe to assume that if you're using bignumber.js in your app or library and have users on latest stable iOS/Safari browsers any calculations in the last 30ish days could be inaccurate...... 😱

**Comment by MikeMcl** [comment] 2017-05-03 18:37
I've published v4.0.2 which uses Jamie's above workaround to resolve the issue.

**Comment by dfrencham** [comment] 2017-05-03 21:40
@jamsinclair all tests are passing here mate. The failing tests are a bit of a worry, we count our user base in the millions, with a significant percentage using IOS.

@MikeMcl thanks for pushing that through, much appreciated!

**Comment by krachtstefan** [comment] 2017-05-04 06:35
Thanks @MikeMcl and all that helped with this issue! Can you tag the latest release with `v4.0.1`. I'm just asking for a `bower.json` file ;)

**Comment by jimgrimmett** [comment] 2017-05-04 10:40
Sufferring from this exact bug in our live instance now. Any chance of a release or does it need more testing?

**Comment by MikeMcl** [comment] 2017-05-04 19:04
@krachtstefan 

It's tagged `v4.0.2` and I've just pushed it now.
Thanks for the reminder.

**Comment by brendan-roche** [comment] 2017-05-24 04:52
hi @MikeMcl, does this fix also need to be backported to Big.js?

**Comment by MikeMcl** [comment] 2017-05-24 09:13
@brendan-roche 

It is quite possible that big.js, bignumber.js and decimal.js-light are also affected.
That is one of the reasons I was reluctant to apply a fix here.
If you find that the bug causes problems with big.js, please raise the issue there.

**Closed** 2017-06-03 21:35 UTC
